### ISSUE TITLE
update documentation to describe use of query parameter in Rest API

### ISSUE THREAD

**Issue by vlouvet** [jacobsvante/netsuite#30]
The use of the query parameter in the REST API part of the library is not well documented.

For example, one could search for a customer containing a keyword in the name by using the code below:

```
customer_keyword = 'Test Customer'
query_params = {'q':f'Name CONTAIN "{customer_keyword }"'}
rest_api_results = await ns.rest_api.get("/record/v1/customer", params=query_params)
```

It would be helpful to include this information in the 'Programmatic Use' section of the Docs

**Comment by iloveitaly** [comment]
Want to submit a PR for this?

**Comment by vlouvet** [comment]
Yes, @jacobsvante I would like to create a PR for this issue, but in the meantime - I will attach the updated /docs/index.md file with my changes.

[index.md](https://github.com/jacobsvante/netsuite/files/13756294/index.md)

Let me know if I should fork and then do a PR from my fork to one of the branches on this repository - happy to help however I can.
