### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by jacobsvante** [jacobsvante/netsuite#49]
Hi everyone,

I haven't been very active in the Python community these last two years and as a consequence this project hasn't received the love that it deserves.

@iloveitaly who maintains the Ruby project with the same name reached out to me a week ago and asked if he could help. Naturally I accepted his offer and he is as of today a maintainer of this project. He also has access to PyPI so he can push new versions out.

So I'd like to extend a big warm welcome to @iloveitaly!

Have a nice day everyone and see you around 👋

**Comment by VeNoMouS** [comment]
sweet, can we go back to pre-async? :) ~== 0.5.3
