### ISSUE TITLE
Unable to use netsuite soap dependencies , pip installation functionality is broken 

### ISSUE THREAD

**Issue by anuragbisht-turing** [jacobsvante/netsuite#82]
When I try to install soap_api dependencies I get no matches found error 

<img width="896" alt="Screenshot 2024-02-05 at 12 16 56 AM" src="https://github.com/jacobsvante/netsuite/assets/97904101/dd902e40-5984-462c-98a9-6a64daa3aa68">

Please help in this regard

**Comment by jklinect** [comment]
Your shell is trying to act on the `[]` characters. Add quotes around the package name to prevent that:

```shellsession
% pipx install netsuite[all]
zsh: no matches found: netsuite[all]
% pipx install 'netsuite[all]' 
  installed package netsuite 0.11.0, installed using Python 3.12.1
  These apps are now globally available
    - netsuite
```

**Comment by iloveitaly** [comment]
Looks like the right fix to me—closing this out.
